# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bfe096bf2dd97656db36ec979070ac96408eb5f8ca1695b6fa43ab51d367654ee4497b30ff223f1019af8186eb5d4c01a599fdf05824ed2c015f9ec66e46ad7

test:
  secret_key_base: 8d67a287ba9b21d44fe2aad897890418c04c0a38e02fc854a80eaf3add5700cda211c2656cc88ddb7a64085c29f0cfb4e39e6d3c9ecba1dbeb6af538c612d724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
