# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e036771f1c01f7b758e30e02521ab5defe0144f77adccc117255680a8ea70183aeb12966f24d13a23d28f4f2771bb81deec6bb0a0583d7c03e6d804495e3b8

test:
  secret_key_base: f8972a6ada73f6f0b62d0ba744d6f50ce4e871a96e1895216fd77d2b2ba7e6f2a0300c7fc63c016012d05e0a4245a8b92241c813378089715ea1b1e1d32fd0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
